/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Courses extends javax.swing.JFrame {

    /**
     * Creates new form Courses
     */
    Connection c;
    Statement s;
    PreparedStatement ps;
    public Courses(String value) {
        try {
            initComponents();
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/college","root","");
            s=c.createStatement();
            String sql="select * from student where id='"+value+"'";
            ResultSet rs= s.executeQuery(sql);
            while(rs.next()){
                id.setText(rs.getString(1));
                course1.setSelectedItem(rs.getString(9));
                course2.setSelectedItem(rs.getString(10));
                course3.setSelectedItem(rs.getString(11));
                course4.setSelectedItem(rs.getString(12));
                course5.setSelectedItem(rs.getString(13));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Courses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Sql Exception", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        course1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        course2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        course3 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        course4 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        course5 = new javax.swing.JComboBox();
        id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Course 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 60, 14);

        course1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DataStructure", "Algorithm", "InroductionToComputers", "MobileApplication", "Artificial Intelligence", "Assembly Language", "Compilers" }));
        getContentPane().add(course1);
        course1.setBounds(90, 65, 220, 30);

        jLabel2.setText("Course 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 60, 14);

        course2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Calcus1", "Calcus2", "LinearAlgebra", "Logic Design", "Data Mining", "Computer Animation" }));
        getContentPane().add(course2);
        course2.setBounds(90, 103, 218, 30);

        jLabel3.setText("Course 3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 60, 14);

        course3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SoftwareEnigneer", "AnalysisAndDesignOfInformationSystem", "C++", "Java", "Python", "Robotics" }));
        getContentPane().add(course3);
        course3.setBounds(90, 141, 218, 30);

        jLabel4.setText("Course 4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 60, 14);

        course4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "InternetApplication", "E-Commerce", "DataBase", "Computer Graphics-1", "Computer Graphics-2", "E-Learning" }));
        getContentPane().add(course4);
        course4.setBounds(90, 179, 218, 30);

        jLabel5.setText("Course 5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 230, 60, 14);

        course5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Programming2", "AdvancedDatabase", "Physics", "Internet Technology", "Wireless and Mobile Networks", "Virtual Reality", "Software Engineering-2" }));
        getContentPane().add(course5);
        course5.setBounds(90, 217, 218, 30);

        id.setEnabled(false);
        getContentPane().add(id);
        id.setBounds(90, 11, 218, 30);

        jLabel6.setText("ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 20, 30, 14);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 270, 90, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 270, 80, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 270, 90, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/college","root","");
            s=c.createStatement();
            String sql="UPDATE  student set Course1='"+course1.getSelectedItem()+"',Course2='"+course2.getSelectedItem()+"',Course3='"+course3.getSelectedItem()+"',Course4='"+course4.getSelectedItem()+"',Course5='"+course5.getSelectedItem()+"' WHERE ID="+Integer.parseInt(id.getText());
            
            ps=c.prepareStatement(sql);
            
            int i=ps.executeUpdate();
            if(i==1){
                JOptionPane.showMessageDialog(null,"Courses Has Been Regiested", "Confirmation",JOptionPane.INFORMATION_MESSAGE);
                int k=Integer.parseInt(id.getText());
                NewW w=new NewW(k);
                this.dispose();
               w.setSize(850, 400);
               w.setLocation(300,200);
               w.setVisible(true);
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Error in Regesting", "Error",JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Sql Exception", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                    this.dispose();
                     SearchEngine s=new SearchEngine();
                     s.setLocation(500, 200);
                    s.setSize(400,300);
                    s.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Courses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox course1;
    private javax.swing.JComboBox course2;
    private javax.swing.JComboBox course3;
    private javax.swing.JComboBox course4;
    private javax.swing.JComboBox course5;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    
}
